version: '3.1'
services:
  rabbitmq:
    container_name: 'rabbit-mq'
    image: rabbitmq:3.11.3-management-alpine
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes:
      - ./rabbitmq-config/definitions.json:/etc/rabbitmq/definitions.json:ro
      - ./rabbitmq-config/rabbitmq.config:/etc/rabbitmq/rabbitmq.config:ro
    profiles:
      - online-shop
      - rabbit
  discovery-service:
    container_name: 'discovery-service'
    image: 'discovery-service'
    ports:
      - '8761:8761'
    profiles:
      - online-shop
      - main
  gateway-service:
    container_name: 'gateway-service'
    image: 'gateway-service'
    ports:
      - '8080:8080'
    profiles:
      - online-shop
      - main
  order-service:
    container_name: 'order-service'
    image: 'order-service'
    ports:
      - '8090:8090'
    profiles:
      - online-shop
  payment-service:
    container_name: 'payment-service'
    image: 'payment-service'
    ports:
      - '8091:8091'
    profiles:
      - online-shop