server:
  port: 8090
spring:
  rabbitmq:
    host: rabbit-mq
  application:
    name: order-service
  datasource:
    url: jdbc:postgresql://database:5432/order_service
    username: postgres
    password: postgres123
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/
